### ISSUE TITLE
Triggered infinitely by an SCM change

### ISSUE THREAD

**Issue by abcfy2** [DABSquared/gitlab-plugin#30]
When this plugin triggered build, offten build infinitely by an SCM change unless I abort the build job.

Here is some screenshort:

![deepinscreenshot20141126193856](https://cloud.githubusercontent.com/assets/5327677/5200733/efe732c4-75a3-11e4-93b9-eb44d04ca89d.png)
![deepinscreenshot20141126193916](https://cloud.githubusercontent.com/assets/5327677/5200734/f9bf6032-75a3-11e4-8a66-2cf948538d36.png)

What's wrong?

**Comment by p00j4** [comment]
Started getting the same today 
On latest 

```
Jenkins ver. 2.190.1
```
![image](https://user-images.githubusercontent.com/6470509/74313307-74045f00-4d99-11ea-80f1-e392eaee6e34.png)

It's giving nightmare with infinite builds marked as "Started by an SCM change" even if I start the build myself, one build is triggered on my name followed by infinite triggers by "SCM change" and there is no change in code at all.

Seeing these weird new lines 
```
Multiple candidate revisions
Scheduling another build to catch up with
``` 
like https://issues.jenkins-ci.org/browse/JENKINS-54102?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
And this is happening for master branch but we don't have any "origin/master" branch as suggested workaround here https://issues.jenkins-ci.org/browse/JENKINS-21464?focusedCommentId=250183&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-250183

Any workaround?

**Comment by p00j4** [comment]
**Update** Even when we didn't have origin/master, replacing the wildcard find "*/master" with "master" in "Branches to build" fixes the issue. But, I have been using the same since the ages (8 years now) and the wildcard has never given me this issue before. 
This surely is a bug with git jenkins plugin, reported here https://issues.jenkins-ci.org/browse/JENKINS-61065
Sorry for waking up this thread
